### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by SeaTheMiner** [ShazamHax/Snay-bots#1]
can u make a script that spams all the emojis in the game? or only a set of the emojis

i wanna spam the pepe emojis

**Comment by ShazamHax** [comment]
> can u make a script that spams all the emojis in the game? or only a set of the emojis
> 
> i wanna spam the pepe emojis

Yes I can definitely do that if you are still interested! I can maybe create an option in the mod menu to turn on a keybind.
When pressed it can spam all the emojis that you have. Or one particular emoji sounds better?

**Comment by SeaTheMiner** [comment]
Either will be great, but if possible in a separate script and open sourced, thank you!

**Comment by ShazamHax** [comment]
> Either will be great, but if possible in a separate script and open sourced, thank you!

I'm not sure why you want me to put it in a seperate script. Also this is open source. It is obfuscated but the code is right there. I can de-obfuscate the code and add the feature if you want.

**Comment by ShazamHax** [comment]
> Either will be great, but if possible in a separate script and open sourced, thank you!

Alright I have created a new button in the mod menu, when clicked it will spam all emojis randomly! Let me know if this is what you had in mind.

**Comment by SeaTheMiner** [comment]
> > Either will be great, but if possible in a separate script and open sourced, thank you!
> 
> Alright I have created a new button in the mod menu, when clicked it will spam all emojis randomly! Let me know if this is what you had in mind.

Thank you, and for the deobfuscation it was because it was being marked as a malicious script and i couldnt use it, so i was worried.

**Comment by ShazamHax** [comment]
> > > Either will be great, but if possible in a separate script and open sourced, thank you!
> > 
> > 
> > Alright I have created a new button in the mod menu, when clicked it will spam all emojis randomly! Let me know if this is what you had in mind.
> 
> Thank you, and for the deobfuscation it was because it was being marked as a malicious script and i couldnt use it, so i was worried.

Oh damn okay well yes you can have a look through the code for yourself in the ScriptCode.js file. That is all the code being executed in the script.
